import assert from 'node:assert/strict';

const url = process.env.ENGINE_TEST_URL || 'http://127.0.0.1:8000';
assert.ok(['127.0.0.1', 'localhost'].includes(new URL(url).hostname));
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) });

try {
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.evaluate(() => {
    const layout = {
      items: [
        { type: 'round', nodeId: 'table-original', inventoryName: '30" Round Cocktail Table', cocktailHeightMode: 'H', color: '#8b44bb', diameter: 2.5, unit: 'ft', x: 650, y: 160 },
        { type: 'chair', nodeId: 'chair-untouched', inventoryName: 'Chiavari Chair', color: '#cba763', width: 1.5, length: 1.5, unit: 'ft', x: 850, y: 160 },
        { type: 'label', itemKind: 'label', nodeId: 'label-high-top', text: 'H', x: 650, y: 160, attachedToNodeId: 'table-original', autoGenerated: true, labelKind: 'item-detail' },
        { type: 'label', itemKind: 'label', nodeId: 'label-untouched', text: 'Keep me', x: 850, y: 160, attachedToNodeId: 'chair-untouched' },
        { type: 'groupedSeating', itemKind: 'grouped_seating', nodeId: 'seating-untouched', x: 1200, y: 300, groupedConfig: { layoutKind: 'table_seating', tableName: '60" Round Table', chairName: 'Chiavari Chair', chairCount: 8, clearanceFt: .25, tableChairPattern: 'side_by_side', seatingLabel: 'Guests' } },
        { type: 'pipeDrapeChain', itemKind: 'pipe_drape_chain', nodeId: 'pipe-untouched', points: [{ x: 1300, y: 300 }, { x: 1396, y: 300 }], heightFt: 10, crossbarMinFt: 6, crossbarMaxFt: 10, pipeDrapeSetupName: 'Backdrop' },
        { type: 'fenceChain', itemKind: 'fence_chain', nodeId: 'fence-untouched', points: [{ x: 1300, y: 400 }, { x: 1396, y: 400 }], panelLengthFt: 8, fenceSetupName: 'Perimeter' },
        { type: 'drawnRun', itemKind: 'drawn_run', nodeId: 'light-untouched', drawMode: 'bistro', color: '#f1c75b', runPoints: [{ x: 1300, y: 500 }, { x: 1540, y: 500 }], lightRunName: 'Patio' },
      ],
      venues: [{ type: 'tent', nodeId: 'venue-untouched', x: 1000, y: 160, width: 20, height: 20, unit: 'ft' }],
    };
    localStorage.setItem('event-floorplanner:documents:v1', JSON.stringify([{ id: 88003, title: 'History regression', layout }]));
  });
  await page.goto(`${url}/?id=88003`);
  await page.waitForFunction(() => window.Konva?.stages[0]?.find('.item').length === 2 && window.Konva.stages[0].find('.label').length === 2);

  const state = () => page.evaluate(() => {
    const stage = window.Konva.stages[0];
    const nodes = stage.find('.item').filter(node => node.getAttr('customType') === 'item');
    const labels = stage.find('.label').filter(node => node.getAttr('customType') === 'label');
    const venue = stage.find('.venue').find(node => node.getAttr('nodeId') === 'venue-untouched');
    const item = id => nodes.find(node => node.getAttr('nodeId') === id);
    const label = id => labels.find(node => node.getAttr('nodeId') === id);
    return {
      items: nodes.map(node => ({ id: node.getAttr('nodeId'), color: node.getAttr('itemColor'), fill: node.fill ? node.fill() : undefined, x: node.x(), y: node.y() })),
      labels: labels.map(node => ({ id: node.getAttr('nodeId'), text: node.getAttr('labelText'), attachedTo: node.getAttr('attachedToNodeId') })),
      untouched: {
        chair: { color: item('chair-untouched')?.getAttr('itemColor'), x: item('chair-untouched')?.x(), y: item('chair-untouched')?.y() },
        label: { text: label('label-untouched')?.getAttr('labelText'), attachedTo: label('label-untouched')?.getAttr('attachedToNodeId') },
        venue: { x: venue?.x(), y: venue?.y(), width: venue?.getAttr('widthFt') },
        seating: stage.find('.groupedSeating').find(node => node.getAttr('nodeId') === 'seating-untouched')?.getAttr('groupedConfig'),
        pipe: stage.find('.pipeDrapeChain').find(node => node.getAttr('nodeId') === 'pipe-untouched')?.getAttr('pipeDrapePoints'),
        fence: stage.find('.fenceChain').find(node => node.getAttr('nodeId') === 'fence-untouched')?.getAttr('fencePoints'),
        light: stage.find('.drawnRun').find(node => node.getAttr('nodeId') === 'light-untouched')?.getAttr('runPoints'),
      },
    };
  });

  const initial = await state();
  assert.equal(initial.items.find(item => item.id === 'table-original').color, '#8b44bb');
  assert.equal(initial.labels.find(label => label.id === 'label-high-top').text, 'H');
  const clickItem = async (id, offsetX = 0, offsetY = 0) => {
    const point = await page.evaluate(({ id, offsetX, offsetY }) => {
      const stage = window.Konva.stages[0];
      const node = stage.find('.item').find(item => item.getAttr('nodeId') === id);
      const position = node.getAbsolutePosition();
      const rect = stage.container().getBoundingClientRect();
      return { x: rect.left + position.x + offsetX, y: rect.top + position.y + offsetY };
    }, { id, offsetX, offsetY });
    await page.mouse.click(point.x, point.y);
  };
  await clickItem('table-original', -10);
  await page.locator('#copyBtn').click();
  await page.locator('#pasteBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 3);
  const pasted = await state();
  const copy = pasted.items.find(item => !['table-original', 'chair-untouched'].includes(item.id));
  assert.equal(copy?.color, '#8b44bb', 'copied table keeps its color');
  assert.equal(copy?.fill, '#8b44bb', 'copied table renders in its original color');
  assert.ok(pasted.labels.some(label => label.text === 'H' && label.attachedTo === copy.id), 'copied H label follows copied table');
  assert.deepEqual(pasted.items.find(item => item.id === 'table-original'), initial.items.find(item => item.id === 'table-original'), 'paste leaves the source item unchanged');
  assert.deepEqual(pasted.untouched, initial.untouched, 'paste leaves unrelated objects unchanged');
  await page.evaluate(() => {
    const stage = window.Konva.stages[0];
    window.__historyUntouchedChair = stage.find('.item').find(node => node.getAttr('nodeId') === 'chair-untouched');
    window.__historyUntouchedLabel = stage.find('.label').find(node => node.getAttr('nodeId') === 'label-untouched');
  });

  await page.locator('#undoBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 2);
  const undone = await state();
  assert.deepEqual(undone.untouched, initial.untouched, 'undo leaves unrelated objects unchanged');
  const preservedAfterUndo = await page.evaluate(() => {
    const stage = window.Konva.stages[0];
    const chair = stage.find('.item').find(node => node.getAttr('nodeId') === 'chair-untouched');
    const label = stage.find('.label').find(node => node.getAttr('nodeId') === 'label-untouched');
    return {
      chair: chair === window.__historyUntouchedChair,
      label: label === window.__historyUntouchedLabel,
    };
  });
  assert.deepEqual(preservedAfterUndo, { chair: true, label: true }, 'undo keeps unrelated canvas nodes intact');
  assert.ok(undone.labels.some(label => label.id === 'label-high-top' && label.text === 'H'), 'undo retains original H label');
  assert.equal(undone.items.find(item => item.id === 'table-original').color, '#8b44bb', 'undo retains original color');

  await page.locator('#redoBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 3);
  const redone = await state();
  assert.deepEqual(redone.untouched, initial.untouched, 'redo leaves unrelated objects unchanged');
  assert.equal(await page.evaluate(() => window.Konva.stages[0].find('.item').find(node => node.getAttr('nodeId') === 'chair-untouched') === window.__historyUntouchedChair), true, 'redo keeps unrelated canvas nodes intact');
  assert.ok(redone.labels.some(label => label.text === 'H' && label.attachedTo === copy.id), 'redo restores copied H label');
  assert.equal(redone.items.find(item => item.id === copy.id).color, '#8b44bb', 'redo restores copied color');
  assert.equal(redone.items.find(item => item.id === copy.id).fill, '#8b44bb', 'redo restores the copied table fill');

  await page.locator('#labelsToggleBtn').click();
  await clickItem('chair-untouched', 2, 2);
  await page.locator('#copyBtn').click();
  await page.locator('#pasteBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 4);
  assert.equal((await state()).items.find(item => !['table-original', 'chair-untouched', copy.id].includes(item.id)).color, '#cba763', 'copied chair keeps its color');
  await page.locator('#undoBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 3);
  assert.ok((await state()).items.some(item => item.id === copy.id), 'undo removes only the last pasted item');
  await page.locator('#labelsToggleBtn').click();

  await page.locator('#savePlannerMenuItem').evaluate(button => button.click());
  await page.reload();
  await page.waitForFunction(() => window.Konva?.stages[0]?.find('.item').length === 3);
  const reloaded = await state();
  assert.equal(reloaded.items.find(item => item.id === 'table-original').color, '#8b44bb', 'save/reload keeps table color');
  assert.equal(reloaded.items.find(item => item.id === 'table-original').fill, '#8b44bb', 'save/reload keeps the table fill');
  assert.equal(reloaded.items.find(item => item.id === 'chair-untouched').color, '#cba763', 'save/reload keeps chair color');
  assert.ok(reloaded.labels.some(label => label.id === 'label-high-top' && label.text === 'H'), 'save/reload keeps H label');

  await page.evaluate(() => {
    const table = window.Konva.stages[0].find('.item').find(node => node.getAttr('nodeId') === 'table-original');
    table.position({ x: table.x() + 24, y: table.y() + 12 });
    table.fire('dragend', { evt: {} });
  });
  assert.notEqual((await state()).items.find(item => item.id === 'table-original').x, reloaded.items.find(item => item.id === 'table-original').x, 'move changes the selected table');
  await page.locator('#undoBtn').click();
  await page.waitForFunction(expectedX => window.Konva.stages[0].find('.item').find(node => node.getAttr('nodeId') === 'table-original')?.x() === expectedX, reloaded.items.find(item => item.id === 'table-original').x);
  const moveUndone = await state();
  assert.deepEqual(moveUndone.untouched, initial.untouched, 'undoing a move leaves unrelated objects unchanged');
  assert.ok(moveUndone.labels.some(label => label.id === 'label-high-top' && label.text === 'H'), 'undoing a move keeps the H label');

  await page.locator('#settingsMenuItem').evaluate(button => button.click());
  const widthsBefore = await page.evaluate(() => {
    const stage = window.Konva.stages[0];
    return { table: stage.find('.item').find(node => node.getAttr('nodeId') === 'table-original').strokeWidth(), venue: stage.find('.venueWallSegment').find(node => node.getParent().getAttr('nodeId') === 'venue-untouched').strokeWidth() };
  });
  await page.locator('#outlineThickness').evaluate(input => { input.value = '150'; input.dispatchEvent(new Event('input', { bubbles: true })); });
  const widthsAfter = await page.evaluate(() => {
    const stage = window.Konva.stages[0];
    return { table: stage.find('.item').find(node => node.getAttr('nodeId') === 'table-original').strokeWidth(), venue: stage.find('.venueWallSegment').find(node => node.getParent().getAttr('nodeId') === 'venue-untouched').strokeWidth() };
  });
  assert.equal(widthsAfter.table, widthsBefore.table * 1.5);
  assert.equal(widthsAfter.venue, widthsBefore.venue * 1.5);
  await page.reload();
  await page.waitForFunction(() => window.Konva?.stages[0]?.find('.item').length === 3);
  assert.equal(await page.locator('#outlineThickness').inputValue(), '150', 'line thickness persists in this browser');
  assert.equal(await page.evaluate(() => window.Konva.stages[0].find('.item').find(node => node.getAttr('nodeId') === 'table-original').strokeWidth()), widthsAfter.table, 'line thickness applies after reload');

  await page.goto(url);
  await page.waitForFunction(() => !!window.Konva?.stages[0]);
  const highTopButton = page.locator('[data-cocktail-height-mode="H"]').first();
  await page.waitForFunction(() => !!document.querySelector('[data-cocktail-height-mode="H"]'));
  await highTopButton.evaluate(button => button.click());
  const placementPoint = await page.evaluate(() => {
    const rect = window.Konva.stages[0].container().getBoundingClientRect();
    return { x: rect.left + rect.width * .65, y: rect.top + rect.height * .5 };
  });
  await page.mouse.click(placementPoint.x, placementPoint.y);
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 1 && window.Konva.stages[0].find('.label').length === 1);
  await page.locator('#undoBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 0);
  assert.equal(await page.evaluate(() => window.Konva.stages[0].find('.label').length), 0, 'one undo removes the placed table and its H label together');
  await page.locator('#redoBtn').click();
  await page.waitForFunction(() => window.Konva.stages[0].find('.item').length === 1);
  assert.equal(await page.evaluate(() => window.Konva.stages[0].find('.label').length), 1, 'one redo restores the placed table and H label together');
  assert.deepEqual(errors, []);
  console.log('Copy/paste, one-step undo/redo, labels, colors, unrelated objects, and line thickness passed.');
} finally {
  await browser.close();
}
